version: '3.8'
services:
  backend1:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo1

  mongo1:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - vol1:/data/db
 
volumes:
  vol1:
